name: awsmorty
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed: ^2.4.2
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1
  dio: ^5.3.2
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  either_dart: ^1.0.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  lottie: ^2.6.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/
